# Generated by Django 6.0.3 on 2026-03-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oak_lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='image_emoji',
        ),
        migrations.AddField(
            model_name='creature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='creatures/'),
        ),
    ]
